//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Collections.Generic;
using System;
using System.Web;

namespace MVCcafe_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int adminID { get; set; }
    
        public string aName { get; set; }

        public string aPwd { get; set; }
    }
}
