
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MVC_web.Models.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Item
{

    public int itemID { get; set; }

    public string itemType { get; set; }

    public string itemName { get; set; }

    public string iDesc { get; set; }

    public string iStatus { get; set; }

    public int iPrice { get; set; }

    public int qty { get; set; }

    public byte[] imgdata { get; set; }

}

}
