
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MVC_web.Models.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public int orderID { get; set; }

    public System.DateTime orderDate { get; set; }

    public System.TimeSpan orderTime { get; set; }

    public byte[] timestamp { get; set; }

    public string orderStatus { get; set; }

}

}
