
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MVC_web.Models.DB
{

using System;
    using System.Collections.Generic;
    
public partial class OrderItem
{

    public int OrderID { get; set; }

    public int itemID { get; set; }

    public int itemQty { get; set; }

    public System.DateTime lastUpdateDate { get; set; }



    public virtual Item Item { get; set; }

    public virtual Order Order { get; set; }

}

}
